# Generated by Django 4.2.8 on 2023-12-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_spec',
            new_name='service_description',
        ),
    ]
