# Generated by Django 4.2.8 on 2023-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_service_spec_service_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.CharField(max_length=355),
        ),
    ]
