# Generated by Django 4.2.8 on 2023-12-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='v_category',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_on',
            field=models.DateField(auto_now=True),
        ),
    ]
