# Generated by Django 4.2.8 on 2023-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_v_category_booking_booked_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='cat_name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default='default_image.jpg', upload_to='vehicles'),
        ),
    ]
