# Generated by Django 4.2.8 on 2023-12-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_category_name_category_cat_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='category_name',
        ),
    ]
