# Generated by Django 4.2.8 on 2024-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_price',
            field=models.IntegerField(default=0),
        ),
    ]
